package org.sc.utils;

public enum Patentes {
	
	RECRUTA(), SOLDADO(), SOLDADO1CLASSE(), CABO(), SARGENTO3(), SARGENTO2(), SARGENTO1(), SUBTENENTE(), ASPIRANTE(), TENENTE2(), TENENTE1(),
	CAPITAO(), MAJOR(), TENCORONEL(), CORONEL(), CAPELAO(); 
	

}
