/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.sc.views;

import javax.swing.JMenuBar;

/**
 * 
 * @author Wesley
 */
public class Aplication extends SwitchablePanel {

   /**
    * Creates new form Aplication
    * 
    * @param frame
    */
   private final JMenuBar menuMain;

   public Aplication(Window frame, JMenuBar menu) {
      super(frame, false);
      initComponents();
      this.menuMain = menu;
      menuMain.setVisible(true);

   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed"
   // desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      upBar = new javax.swing.JPanel();
      jLabel1 = new javax.swing.JLabel();
      jLabel2 = new javax.swing.JLabel();
      jLabel3 = new javax.swing.JLabel();
      jButton1 = new javax.swing.JButton();
      jPanel1 = new javax.swing.JPanel();
      jButton2 = new javax.swing.JButton();
      panelMenu = new javax.swing.JPanel();

      setPreferredSize(new java.awt.Dimension(1000, 600));

      upBar.setAlignmentX(1.0F);
      upBar.setAlignmentY(1.0F);
      upBar.setName(""); // NOI18N
      upBar.setPreferredSize(new java.awt.Dimension(950, 50));

      jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      jLabel1.setText("Olá, ");

      jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
      jLabel2.setText("Wesley Nunes");

      jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      jLabel3.setText("batalhão");

      jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
            "/images/exitIcon.png"))); // NOI18N
      jButton1.setOpaque(false);
      jButton1.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout upBarLayout = new javax.swing.GroupLayout(upBar);
      upBar.setLayout(upBarLayout);
      upBarLayout
            .setHorizontalGroup(
            upBarLayout
                  .createParallelGroup(
                        javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(
                        upBarLayout
                              .createSequentialGroup()
                              .addGap(21, 21, 21)
                              .addComponent(jLabel1)
                              .addPreferredGap(
                                    javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel2,
                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                    133, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(274, 274, 274)
                              .addComponent(jLabel3,
                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                    190, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(
                                    javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                    276, Short.MAX_VALUE)
                              .addComponent(jButton1,
                                    javax.swing.GroupLayout.PREFERRED_SIZE, 50,
                                    javax.swing.GroupLayout.PREFERRED_SIZE))
            );
      upBarLayout
            .setVerticalGroup(
            upBarLayout
                  .createParallelGroup(
                        javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(
                        upBarLayout
                              .createSequentialGroup()
                              .addContainerGap()
                              .addGroup(
                                    upBarLayout
                                          .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING)
                                          .addComponent(
                                                jLabel2,
                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)
                                          .addComponent(
                                                jLabel1,
                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)
                                          .addComponent(
                                                jLabel3,
                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE))
                              .addContainerGap())
                  .addGroup(
                        javax.swing.GroupLayout.Alignment.TRAILING,
                        upBarLayout
                              .createSequentialGroup()
                              .addComponent(jButton1,
                                    javax.swing.GroupLayout.PREFERRED_SIZE, 50,
                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(0, 0, Short.MAX_VALUE))
            );

      jButton2.setBackground(new java.awt.Color(153, 255, 255));
      jButton2.setText("jButton2");
      jButton2.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton2ActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
            jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(
                  javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE,
                        239, Short.MAX_VALUE)
            );
      jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(
                  javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(
                        jPanel1Layout
                              .createSequentialGroup()
                              .addGap(46, 46, 46)
                              .addComponent(jButton2,
                                    javax.swing.GroupLayout.PREFERRED_SIZE, 44,
                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addContainerGap(209, Short.MAX_VALUE))
            );

      javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(
            panelMenu);
      panelMenu.setLayout(panelMenuLayout);
      panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(
                  javax.swing.GroupLayout.Alignment.LEADING)
                  .addGap(0, 0, Short.MAX_VALUE)
            );
      panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(
                  javax.swing.GroupLayout.Alignment.LEADING)
                  .addGap(0, 55, Short.MAX_VALUE)
            );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
            layout.createParallelGroup(
                  javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(
                        layout.createSequentialGroup()
                              .addContainerGap()
                              .addGroup(
                                    layout.createParallelGroup(
                                          javax.swing.GroupLayout.Alignment.LEADING)
                                          .addComponent(
                                                upBar,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                980, Short.MAX_VALUE)
                                          .addGroup(
                                                layout.createSequentialGroup()
                                                      .addGap(14, 14, 14)
                                                      .addComponent(
                                                            jPanel1,
                                                            javax.swing.GroupLayout.PREFERRED_SIZE,
                                                            javax.swing.GroupLayout.DEFAULT_SIZE,
                                                            javax.swing.GroupLayout.PREFERRED_SIZE)
                                                      .addGap(0, 0,
                                                            Short.MAX_VALUE))
                                          .addComponent(
                                                panelMenu,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE))
                              .addContainerGap())
            );
      layout.setVerticalGroup(
            layout.createParallelGroup(
                  javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(
                        layout.createSequentialGroup()
                              .addContainerGap()
                              .addComponent(panelMenu,
                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(51, 51, 51)
                              .addComponent(upBar,
                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(50, 50, 50)
                              .addComponent(jPanel1,
                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addContainerGap(84, Short.MAX_VALUE))
            );
   }// </editor-fold>//GEN-END:initComponents

   private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
      // TODO add your handling code here:
      getMainFrame().switchPanels(new Home(getMainFrame(), menuMain));
   }// GEN-LAST:event_jButton1ActionPerformed

   private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
      // TODO add your handling code here:
      getMainFrame().switchPanels(new Registry(getMainFrame()));
   }// GEN-LAST:event_jButton2ActionPerformed

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton jButton1;
   private javax.swing.JButton jButton2;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JPanel panelMenu;
   private javax.swing.JPanel upBar;
   // End of variables declaration//GEN-END:variables
}
