/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.sc.views;


/**
 * 
 * @author Wesley
 */
public class Aplication extends SwitchablePanel {

   /**
    * Creates new form Aplication
    * 
    * @param frame
    */

   public Aplication(Window frame) {
      super(frame, false);
      initComponents();

   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed"
   // <editor-fold defaultstate="collapsed"
   // <editor-fold defaultstate="collapsed"
   // desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jPopupMenu1 = new javax.swing.JPopupMenu();
      jMenu1 = new javax.swing.JMenu();
      jButton2 = new javax.swing.JButton();
      jButton3 = new javax.swing.JButton();
      jButton4 = new javax.swing.JButton();
      jLabel1 = new javax.swing.JLabel();

      jMenu1.setText("jMenu1");
      jPopupMenu1.add(jMenu1);

      setPreferredSize(new java.awt.Dimension(1000, 600));

      jButton2.setBackground(new java.awt.Color(145, 0, 143));
      jButton2.setForeground(new java.awt.Color(255, 255, 255));
      jButton2.setText("jButton2");
      jButton2.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton2ActionPerformed(evt);
         }
      });

      jButton3.setBackground(new java.awt.Color(145, 0, 143));
      jButton3.setForeground(new java.awt.Color(255, 255, 255));
      jButton3.setText("jButton2");
      jButton3.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton3ActionPerformed(evt);
         }
      });

      jButton4.setBackground(new java.awt.Color(145, 0, 143));
      jButton4.setForeground(new java.awt.Color(255, 255, 255));
      jButton4.setText("jButton2");
      jButton4.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton4ActionPerformed(evt);
         }
      });

      jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
      jLabel1.setForeground(new java.awt.Color(255, 255, 255));
      jLabel1.setText("Cadastro");
      jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            jLabel1MouseClicked(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
            layout.createParallelGroup(
                  javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(
                        javax.swing.GroupLayout.Alignment.TRAILING,
                        layout.createSequentialGroup()
                              .addContainerGap(401, Short.MAX_VALUE)
                              .addComponent(jButton4,
                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                    303, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(296, 296, 296))
                  .addGroup(
                        layout.createSequentialGroup()
                              .addGroup(
                                    layout.createParallelGroup(
                                          javax.swing.GroupLayout.Alignment.LEADING)
                                          .addGroup(
                                                layout.createSequentialGroup()
                                                      .addGap(35, 35, 35)
                                                      .addComponent(
                                                            jButton2,
                                                            javax.swing.GroupLayout.PREFERRED_SIZE,
                                                            303,
                                                            javax.swing.GroupLayout.PREFERRED_SIZE))
                                          .addGroup(
                                                layout.createSequentialGroup()
                                                      .addGap(61, 61, 61)
                                                      .addComponent(jLabel1)))
                              .addContainerGap(
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    Short.MAX_VALUE))
                  .addGroup(
                        layout.createParallelGroup(
                              javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(
                                    layout.createSequentialGroup()
                                          .addGap(39, 39, 39)
                                          .addComponent(
                                                jButton3,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                303,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addContainerGap(658, Short.MAX_VALUE)))
            );
      layout.setVerticalGroup(
            layout.createParallelGroup(
                  javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(
                        layout.createSequentialGroup()
                              .addGap(38, 38, 38)
                              .addComponent(jLabel1)
                              .addGap(155, 155, 155)
                              .addComponent(jButton4,
                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                    100, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(
                                    javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    Short.MAX_VALUE)
                              .addComponent(jButton2,
                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                    100, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(161, 161, 161))
                  .addGroup(
                        layout.createParallelGroup(
                              javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(
                                    layout.createSequentialGroup()
                                          .addGap(204, 204, 204)
                                          .addComponent(
                                                jButton3,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                100,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addContainerGap(300, Short.MAX_VALUE)))
            );
   }// </editor-fold>//GEN-END:initComponents

   private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel1MouseClicked
      // TODO add your handling code here:
      if (jPopupMenu1.isVisible()) {
         jPopupMenu1.hide();
      } else {
         jPopupMenu1.show(this, 60, 110);
      }

   }// GEN-LAST:event_jLabel1MouseClicked

   private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
      // TODO add your handling code here:
   }// GEN-LAST:event_jButton3ActionPerformed

   private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton4ActionPerformed
      // TODO add your handling code here:
   }// GEN-LAST:event_jButton4ActionPerformed

   private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
      // TODO add your handling code here:

   }// GEN-LAST:event_jButton1ActionPerformed

   private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
      // TODO add your handling code here:
      getMainFrame().switchPanels(new Registry(getMainFrame()));
   }// GEN-LAST:event_jButton2ActionPerformed

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton jButton2;
   private javax.swing.JButton jButton3;
   private javax.swing.JButton jButton4;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JMenu jMenu1;
   private javax.swing.JPopupMenu jPopupMenu1;
   // End of variables declaration//GEN-END:variables
}
