/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.sc.views;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import org.sc.controllers.ConnectionController;
import org.sc.controllers.LoginController;

/**
 * 
 * @author Wesley
 */
public class Login extends SwitchablePanel {

   /**
	 * 
	 */
   private static final long serialVersionUID = 6740384300330336965L;

   /**
    * Creates new form Home
    * 
    * @param frame
    */

   public Login(Window frame) {
      super(frame, false);
      initComponents();
      statusConnect.start();
   }

   Thread statusConnect = new Thread() {
      @Override
      public void run() {
         while (true) {
            setStatusConnection();
            try {
               Thread.sleep(2000);
            } catch (InterruptedException e) {
               // TODO Auto-generated catch block
               e.printStackTrace();
            }

         }
      };
   };

   private void setStatusConnection() {
      ImageIcon image;
      if (ConnectionController.isConnected()) {
         nameStatusNet.setText("Online");
         image = new ImageIcon(getClass().getResource(
               "/images/OKConnection.png"));

      } else {
         nameStatusNet.setText("Offline");
         image = new ImageIcon(getClass().getResource(
               "/images/cautionConnection.png"));
      }
      pictureStatusNet.setIcon(image);

   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed"
   // <editor-fold defaultstate="collapsed"
   // <editor-fold defaultstate="collapsed"
   // desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jLabel2 = new javax.swing.JLabel();
      jButton1 = new javax.swing.JButton();
      loginName = new javax.swing.JLabel();
      userText = new javax.swing.JTextField();
      pqName = new javax.swing.JLabel();
      pwText = new javax.swing.JPasswordField();
      forgotPw = new javax.swing.JLabel();
      loginButton = new javax.swing.JButton();
      jLabel1 = new javax.swing.JLabel();
      pictureStatusNet = new javax.swing.JLabel();
      nameStatusNet = new javax.swing.JLabel();

      setPreferredSize(new java.awt.Dimension(1000, 600));

      jLabel2.setText("© Copyright");

      jButton1.setText("jButton1");
      jButton1.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
         }
      });

      loginName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      loginName.setForeground(new java.awt.Color(255, 255, 255));
      loginName.setText("Usuário");
      loginName.setPreferredSize(new java.awt.Dimension(130, 45));

      userText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      userText.setPreferredSize(new java.awt.Dimension(59, 45));
      userText.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            userTextActionPerformed(evt);
         }
      });

      pqName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      pqName.setForeground(new java.awt.Color(255, 255, 255));
      pqName.setText("Senha");

      pwText.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            pwTextActionPerformed(evt);
         }
      });

      forgotPw.setForeground(new java.awt.Color(255, 255, 255));
      forgotPw.setText("Esqueceu a Senha?");

      loginButton.setText("Entrar");
      loginButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            loginButtonActionPerformed(evt);
         }
      });

      jLabel1.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
      jLabel1.setForeground(new java.awt.Color(255, 255, 255));
      jLabel1.setText("LOGIN");

      nameStatusNet.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      nameStatusNet.setForeground(new java.awt.Color(255, 255, 255));

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
            layout.createParallelGroup(
                  javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(
                        layout.createSequentialGroup()
                              .addGap(41, 41, 41)
                              .addGroup(
                                    layout.createParallelGroup(
                                          javax.swing.GroupLayout.Alignment.LEADING)
                                          .addGroup(
                                                layout.createSequentialGroup()
                                                      .addGroup(
                                                            layout.createParallelGroup(
                                                                  javax.swing.GroupLayout.Alignment.TRAILING,
                                                                  false)
                                                                  .addGroup(
                                                                        layout.createSequentialGroup()
                                                                              .addComponent(
                                                                                    forgotPw)
                                                                              .addPreferredGap(
                                                                                    javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                    Short.MAX_VALUE)
                                                                              .addComponent(
                                                                                    loginButton,
                                                                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                    87,
                                                                                    javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                  .addGroup(
                                                                        layout.createParallelGroup(
                                                                              javax.swing.GroupLayout.Alignment.LEADING)
                                                                              .addComponent(
                                                                                    pwText,
                                                                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                    235,
                                                                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                              .addComponent(
                                                                                    pqName,
                                                                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                    145,
                                                                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                              .addComponent(
                                                                                    userText,
                                                                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                    235,
                                                                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                              .addComponent(
                                                                                    loginName,
                                                                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                    145,
                                                                                    javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                      .addGap(0, 0,
                                                            Short.MAX_VALUE))
                                          .addGroup(
                                                layout.createSequentialGroup()
                                                      .addComponent(jLabel1)
                                                      .addPreferredGap(
                                                            javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                            javax.swing.GroupLayout.DEFAULT_SIZE,
                                                            Short.MAX_VALUE)
                                                      .addComponent(
                                                            pictureStatusNet,
                                                            javax.swing.GroupLayout.PREFERRED_SIZE,
                                                            26,
                                                            javax.swing.GroupLayout.PREFERRED_SIZE)
                                                      .addPreferredGap(
                                                            javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                      .addComponent(
                                                            nameStatusNet,
                                                            javax.swing.GroupLayout.PREFERRED_SIZE,
                                                            80,
                                                            javax.swing.GroupLayout.PREFERRED_SIZE))))
                  .addGroup(
                        layout.createSequentialGroup()
                              .addContainerGap(492, Short.MAX_VALUE)
                              .addGroup(
                                    layout.createParallelGroup(
                                          javax.swing.GroupLayout.Alignment.LEADING)
                                          .addGroup(
                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                layout.createSequentialGroup()
                                                      .addComponent(jLabel2)
                                                      .addGap(448, 448, 448))
                                          .addGroup(
                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                layout.createSequentialGroup()
                                                      .addComponent(jButton1)
                                                      .addGap(338, 338, 338))))
            );
      layout.setVerticalGroup(
            layout.createParallelGroup(
                  javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(
                        layout.createSequentialGroup()
                              .addGap(24, 24, 24)
                              .addGroup(
                                    layout.createParallelGroup(
                                          javax.swing.GroupLayout.Alignment.LEADING,
                                          false)
                                          .addComponent(
                                                nameStatusNet,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)
                                          .addComponent(
                                                pictureStatusNet,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                26, Short.MAX_VALUE))
                              .addPreferredGap(
                                    javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                    55, Short.MAX_VALUE)
                              .addComponent(jLabel1)
                              .addGap(18, 18, 18)
                              .addComponent(loginName,
                                    javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(
                                    javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(userText,
                                    javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(
                                    javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addGroup(
                                    layout.createParallelGroup(
                                          javax.swing.GroupLayout.Alignment.LEADING,
                                          false)
                                          .addGroup(
                                                layout.createSequentialGroup()
                                                      .addComponent(
                                                            pqName,
                                                            javax.swing.GroupLayout.PREFERRED_SIZE,
                                                            30,
                                                            javax.swing.GroupLayout.PREFERRED_SIZE)
                                                      .addPreferredGap(
                                                            javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                      .addComponent(
                                                            pwText,
                                                            javax.swing.GroupLayout.PREFERRED_SIZE,
                                                            35,
                                                            javax.swing.GroupLayout.PREFERRED_SIZE)
                                                      .addGap(13, 13, 13)
                                                      .addGroup(
                                                            layout.createParallelGroup(
                                                                  javax.swing.GroupLayout.Alignment.BASELINE)
                                                                  .addComponent(
                                                                        loginButton)
                                                                  .addComponent(
                                                                        forgotPw)))
                                          .addGroup(
                                                layout.createSequentialGroup()
                                                      .addGap(277, 277, 277)
                                                      .addComponent(jButton1)))
                              .addGap(34, 34, 34)
                              .addComponent(jLabel2)
                              .addContainerGap(15, Short.MAX_VALUE))
            );
   }// </editor-fold>//GEN-END:initComponents

   private void userTextActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_userTextActionPerformed
      // TODO add your handling code here:
   }// GEN-LAST:event_userTextActionPerformed

   private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_loginButtonActionPerformed

      boolean ValidateUser = false;
      try {

         if (userText.getText().length() == 0) {
            throw new Exception("Insira o Usuário!");
         }
         if (pwText.getPassword().length == 0) {
            throw new Exception("Insira a Senha!");
         }
         ValidateUser = LoginController.login(userText.getText(), new String(
               pwText.getPassword()));
         if (ValidateUser) {
            getMainFrame().switchPanels(
                  new Aplication(getMainFrame()));
         }
      } catch (Exception e) {
         JOptionPane.showMessageDialog(this, e.getMessage());
      }

   }// GEN-LAST:event_loginButtonActionPerformed

   private void pwTextActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_pwTextActionPerformed
      // TODO add your handling code here:
   }// GEN-LAST:event_pwTextActionPerformed

   private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
      getMainFrame().switchPanels(new Aplication(getMainFrame()));
   }// GEN-LAST:event_jButton1ActionPerformed

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JLabel forgotPw;
   private javax.swing.JButton jButton1;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JButton loginButton;
   private javax.swing.JLabel loginName;
   private javax.swing.JLabel nameStatusNet;
   private javax.swing.JLabel pictureStatusNet;
   private javax.swing.JLabel pqName;
   private javax.swing.JPasswordField pwText;
   private javax.swing.JTextField userText;
   // End of variables declaration//GEN-END:variables
}
