/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.sc.window;

import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.lavieri.modelutil.cep.WebServiceCep;
import org.sc.codes.User;
import org.sc.codes.UserRegistry;
import org.sc.data.DataBaseConnect;

/**
 *
 * @author Wesley
 */
public class Registry extends SwitchablePanel {
    
    private User userRegistry = null;
    private final int FOTO = 0;
    private final int DOCUMENTO = 1;
    private final int MAX_TAM_FOTO = 150;//Tamanho limite em Kb para o upload do foto 3x4
    private final int MAX_TAM_DOCUMENTO = 2024;//Tamanho limite em Kb para o upload do Documento

    /**
     * Creates new form Registry
     *
     * @param frame
     */
    public Registry(Window frame) {
        super(frame, false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogInfo = new javax.swing.JDialog();
        personaldata = new javax.swing.JPanel();
        nome = new javax.swing.JLabel();
        nomeText = new javax.swing.JTextField();
        sexo = new javax.swing.JLabel();
        mBox = new javax.swing.JCheckBox();
        fBox = new javax.swing.JCheckBox();
        warName = new javax.swing.JLabel();
        warNameText = new javax.swing.JTextField();
        birthDate = new javax.swing.JLabel();
        bDayText = new javax.swing.JFormattedTextField();
        bat = new javax.swing.JLabel();
        batOption = new javax.swing.JComboBox();
        RG = new javax.swing.JLabel();
        rgText = new javax.swing.JTextField();
        cpf = new javax.swing.JLabel();
        cpfText = new javax.swing.JFormattedTextField();
        bloodType = new javax.swing.JLabel();
        bloddTypeOption = new javax.swing.JComboBox();
        naturalidade = new javax.swing.JLabel();
        natText = new javax.swing.JTextField();
        ufNat = new javax.swing.JLabel();
        UF = new javax.swing.JTextField();
        Nacionalidade = new javax.swing.JLabel();
        nacText = new javax.swing.JTextField();
        patente = new javax.swing.JLabel();
        patOption = new javax.swing.JComboBox();
        status = new javax.swing.JLabel();
        statusOption = new javax.swing.JComboBox();
        photoPanel = new javax.swing.JPanel();
        photoLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        otherdatas = new javax.swing.JTabbedPane();
        endereco = new javax.swing.JPanel();
        cepLabel = new javax.swing.JLabel();
        cepText = new javax.swing.JTextField();
        streetLabel = new javax.swing.JLabel();
        streetText = new javax.swing.JTextField();
        numberLabel = new javax.swing.JLabel();
        numberText = new javax.swing.JTextField();
        districtLabel = new javax.swing.JLabel();
        districtText = new javax.swing.JTextField();
        complementLabel = new javax.swing.JLabel();
        complementText = new javax.swing.JTextField();
        cityLabel = new javax.swing.JLabel();
        cityText = new javax.swing.JTextField();
        stateLabel = new javax.swing.JLabel();
        stateText = new javax.swing.JTextField();
        countryLabel = new javax.swing.JLabel();
        countryText = new javax.swing.JTextField();
        validarCEP = new javax.swing.JLabel();
        contatos = new javax.swing.JPanel();
        phoneLabel = new javax.swing.JLabel();
        typePhone1 = new javax.swing.JComboBox();
        phoneFormat1 = new javax.swing.JFormattedTextField();
        typePhone2 = new javax.swing.JComboBox();
        typePhone3 = new javax.swing.JComboBox();
        phoneFormat2 = new javax.swing.JFormattedTextField();
        phoneFormat3 = new javax.swing.JFormattedTextField();
        emailLabel = new javax.swing.JLabel();
        emailText = new javax.swing.JTextField();
        validEmail = new javax.swing.JLabel();
        redeSocialLabel = new javax.swing.JLabel();
        FacebookText = new javax.swing.JTextField();
        facebookLabel = new javax.swing.JLabel();
        twitterLabel = new javax.swing.JLabel();
        twitterText = new javax.swing.JTextField();
        questionarioSC = new javax.swing.JScrollPane();
        questionarioSCPanel = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        jComboBox8 = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        jComboBox9 = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        jComboBox10 = new javax.swing.JComboBox();
        jLabel21 = new javax.swing.JLabel();
        jComboBox11 = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        jComboBox12 = new javax.swing.JComboBox();
        questionarioSE = new javax.swing.JScrollPane();
        questionarioSEPanel = new javax.swing.JPanel();
        QSClabel1 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        QSClabel2 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        QSClabel3 = new javax.swing.JLabel();
        jComboBox13 = new javax.swing.JComboBox();
        QSClabel4 = new javax.swing.JLabel();
        jComboBox14 = new javax.swing.JComboBox();
        QSClabel5 = new javax.swing.JLabel();
        fatherLabelSE = new javax.swing.JLabel();
        jComboBox15 = new javax.swing.JComboBox();
        motherLabelSE = new javax.swing.JLabel();
        jComboBox16 = new javax.swing.JComboBox();
        jTextField3 = new javax.swing.JTextField();
        QSClabel6 = new javax.swing.JLabel();
        jComboBox17 = new javax.swing.JComboBox();
        QSClabel7 = new javax.swing.JLabel();
        jComboBox18 = new javax.swing.JComboBox();
        QSClabel8 = new javax.swing.JLabel();
        jComboBox19 = new javax.swing.JComboBox();
        QSClabel9 = new javax.swing.JLabel();
        jComboBox20 = new javax.swing.JComboBox();
        QSClabel10 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jComboBox21 = new javax.swing.JComboBox();
        jComboBox23 = new javax.swing.JComboBox();
        QSClabel11 = new javax.swing.JLabel();
        jComboBox24 = new javax.swing.JComboBox();
        QSClabel12 = new javax.swing.JLabel();
        jComboBox25 = new javax.swing.JComboBox();
        QSClabel13 = new javax.swing.JLabel();
        jComboBox26 = new javax.swing.JComboBox();
        jLabel29 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        questionarioP = new javax.swing.JScrollPane();
        quetionarioPpanel = new javax.swing.JPanel();
        QPlabel1 = new javax.swing.JLabel();
        jComboBox22 = new javax.swing.JComboBox();
        QPlabel2 = new javax.swing.JLabel();
        jComboBox27 = new javax.swing.JComboBox();
        QPlabel3 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jComboBox28 = new javax.swing.JComboBox();
        jComboBox29 = new javax.swing.JComboBox();
        jLabel31 = new javax.swing.JLabel();
        jComboBox30 = new javax.swing.JComboBox();
        QPlabel4 = new javax.swing.JLabel();
        jComboBox31 = new javax.swing.JComboBox();
        jLabel32 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        QPlabel5 = new javax.swing.JLabel();
        jComboBox32 = new javax.swing.JComboBox();
        jLabel33 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        saveButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        clearButton = new javax.swing.JButton();
        helpLabel = new javax.swing.JLabel();
        statusProgress = new javax.swing.JProgressBar();
        uploadPhotoLabel = new javax.swing.JLabel();
        infoPhoto = new javax.swing.JLabel();

        dialogInfo.setTitle("Informações de Cadastro");
        dialogInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dialogInfo.setIconImage((new ImageIcon(getClass().getResource("/org/sc/SystemImages/escudoIcon.png"))).getImage());
        dialogInfo.setLocationByPlatform(true);
        dialogInfo.setMinimumSize(new java.awt.Dimension(600, 350));
        dialogInfo.setResizable(false);
        dialogInfo.setType(java.awt.Window.Type.POPUP);

        javax.swing.GroupLayout dialogInfoLayout = new javax.swing.GroupLayout(dialogInfo.getContentPane());
        dialogInfo.getContentPane().setLayout(dialogInfoLayout);
        dialogInfoLayout.setHorizontalGroup(
            dialogInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        dialogInfoLayout.setVerticalGroup(
            dialogInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        setPreferredSize(new java.awt.Dimension(1000, 600));

        personaldata.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Dados Pessoais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        personaldata.setToolTipText("");
        personaldata.setOpaque(false);

        nome.setText("Nome:");

        sexo.setText("Sexo:");

        mBox.setText("M");
        mBox.setOpaque(false);

        fBox.setText("F");
        fBox.setOpaque(false);

        warName.setText("Nome de Guerra:");

        birthDate.setText("Data de Nascimento:");

        try {
            bDayText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        bat.setText("Batalhão:");

        batOption.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        RG.setText("RG:");

        cpf.setText("CPF:");

        try {
            cpfText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        bloodType.setText("Tipo Sanguíneo: ");

        bloddTypeOption.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-" }));

        naturalidade.setText("Naturalidade:");

        ufNat.setText("UF:");

        Nacionalidade.setText("Nacionalidade:");

        patente.setText("Patente:");

        patOption.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Recruta", "Soldado", "Sd. de 1º classe", "Cabo", "3º Sargento", "2º Sargento", "1º Sargento", "Sub Tenente", "Aspirante", "2º Tenente", "1º Tenente", "Capitão", "Major", "Ten. Coronel", "Coronel", "Capelão" }));

        status.setText("Status: ");

        statusOption.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ativado", "Desativado", "Observação" }));

        javax.swing.GroupLayout personaldataLayout = new javax.swing.GroupLayout(personaldata);
        personaldata.setLayout(personaldataLayout);
        personaldataLayout.setHorizontalGroup(
            personaldataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personaldataLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(personaldataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(warName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RG)
                    .addComponent(patente)
                    .addComponent(naturalidade)
                    .addComponent(nome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personaldataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personaldataLayout.createSequentialGroup()
                        .addGroup(personaldataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nomeText, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(personaldataLayout.createSequentialGroup()
                                .addComponent(warNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(birthDate)
                                .addGap(18, 18, 18)
                                .addComponent(bDayText)
                                .addGap(18, 18, 18)
                                .addComponent(bat)))
                        .addGap(18, 18, 18)
                        .addGroup(personaldataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(personaldataLayout.createSequentialGroup()
                                .addComponent(sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fBox)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(batOption, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(personaldataLayout.createSequentialGroup()
                        .addGroup(personaldataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(personaldataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(natText, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(patOption, javax.swing.GroupLayout.Alignment.LEADING, 0, 143, Short.MAX_VALUE))
                            .addComponent(rgText, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(personaldataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(personaldataLayout.createSequentialGroup()
                                .addComponent(status)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(statusOption, 0, 99, Short.MAX_VALUE))
                            .addGroup(personaldataLayout.createSequentialGroup()
                                .addGroup(personaldataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cpf)
                                    .addComponent(ufNat))
                                .addGap(18, 18, 18)
                                .addGroup(personaldataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cpfText, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(UF))))
                        .addGap(18, 18, 18)
                        .addGroup(personaldataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bloodType)
                            .addComponent(Nacionalidade))
                        .addGap(18, 18, 18)
                        .addGroup(personaldataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bloddTypeOption, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nacText)))))
        );
        personaldataLayout.setVerticalGroup(
            personaldataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personaldataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(personaldataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(personaldataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sexo, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                        .addComponent(mBox)
                        .addComponent(fBox))
                    .addComponent(nome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nomeText, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(personaldataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(warName)
                    .addComponent(warNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(birthDate)
                    .addComponent(bDayText, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bat)
                    .addComponent(batOption, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(personaldataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RG)
                    .addComponent(cpf)
                    .addComponent(cpfText, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bloodType)
                    .addComponent(bloddTypeOption, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rgText, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(personaldataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(natText, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(naturalidade)
                    .addComponent(ufNat)
                    .addComponent(UF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nacionalidade)
                    .addComponent(nacText, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(personaldataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patente)
                    .addComponent(patOption, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(status)
                    .addComponent(statusOption, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        photoPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout photoPanelLayout = new javax.swing.GroupLayout(photoPanel);
        photoPanel.setLayout(photoPanelLayout);
        photoPanelLayout.setHorizontalGroup(
            photoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(photoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
        );
        photoPanelLayout.setVerticalGroup(
            photoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(photoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jButton1.setText("Documentos");

        otherdatas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        otherdatas.setPreferredSize(new java.awt.Dimension(800, 221));

        cepLabel.setText("CEP: ");

        cepText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cepTextFocusLost(evt);
            }
        });

        streetLabel.setText("Logradouro: ");

        streetText.setToolTipText("");

        numberLabel.setText("Número: ");

        districtLabel.setText("Bairro: ");

        complementLabel.setText("Complemento:");

        cityLabel.setText("Cidade:");

        stateLabel.setText("Estado:");

        countryLabel.setText("País:");

        validarCEP.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout enderecoLayout = new javax.swing.GroupLayout(endereco);
        endereco.setLayout(enderecoLayout);
        enderecoLayout.setHorizontalGroup(
            enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enderecoLayout.createSequentialGroup()
                .addGroup(enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(enderecoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(streetLabel)
                            .addComponent(districtLabel)
                            .addComponent(cityLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(enderecoLayout.createSequentialGroup()
                                .addComponent(streetText, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(numberLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(numberText, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(enderecoLayout.createSequentialGroup()
                                .addComponent(districtText, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(complementLabel)
                                .addGap(18, 18, 18)
                                .addComponent(complementText))
                            .addGroup(enderecoLayout.createSequentialGroup()
                                .addComponent(cityText, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(stateLabel)
                                .addGap(18, 18, 18)
                                .addComponent(stateText, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(countryLabel)
                                .addGap(18, 18, 18)
                                .addComponent(countryText))))
                    .addGroup(enderecoLayout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(cepLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cepText, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(validarCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(235, Short.MAX_VALUE))
        );
        enderecoLayout.setVerticalGroup(
            enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cepLabel)
                        .addComponent(cepText, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(validarCEP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(streetLabel)
                    .addComponent(streetText, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberLabel)
                    .addComponent(numberText, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(districtLabel)
                    .addComponent(districtText, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(complementLabel)
                    .addComponent(complementText, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityLabel)
                    .addComponent(cityText, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stateLabel)
                    .addComponent(stateText, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(countryLabel)
                    .addComponent(countryText, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        otherdatas.addTab("ENDEREÇO", endereco);

        phoneLabel.setText("Telefones:");

        typePhone1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Responsável", "Pessoal", "Fixo", "Trabalho", " " }));

        try {
            phoneFormat1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        typePhone2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Responsável", "Pessoal", "Fixo", "Trabalho" }));

        typePhone3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Responsável", "Pessoal", "Fixo", "Trabalho" }));

        try {
            phoneFormat2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            phoneFormat3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        emailLabel.setText("Email: ");

        emailText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailTextFocusLost(evt);
            }
        });

        redeSocialLabel.setText("REDES SOCIAIS:");

        facebookLabel.setText("Facebook:");

        twitterLabel.setText("Twitter:");

        javax.swing.GroupLayout contatosLayout = new javax.swing.GroupLayout(contatos);
        contatos.setLayout(contatosLayout);
        contatosLayout.setHorizontalGroup(
            contatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contatosLayout.createSequentialGroup()
                .addGroup(contatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contatosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(phoneLabel))
                    .addGroup(contatosLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(contatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(typePhone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(typePhone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(typePhone3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(contatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(phoneFormat1, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                            .addComponent(phoneFormat2)
                            .addComponent(phoneFormat3))))
                .addGap(64, 64, 64)
                .addGroup(contatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(redeSocialLabel)
                    .addGroup(contatosLayout.createSequentialGroup()
                        .addGroup(contatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(contatosLayout.createSequentialGroup()
                                .addComponent(emailLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(contatosLayout.createSequentialGroup()
                                .addGroup(contatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(facebookLabel)
                                    .addComponent(twitterLabel))
                                .addGap(18, 18, 18)
                                .addGroup(contatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(FacebookText)
                                    .addComponent(twitterText, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(validEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(188, Short.MAX_VALUE))
        );
        contatosLayout.setVerticalGroup(
            contatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contatosLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(contatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneLabel)
                    .addComponent(emailLabel)
                    .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(validEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(contatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contatosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(contatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(typePhone1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneFormat1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(contatosLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(redeSocialLabel)))
                .addGap(18, 18, 18)
                .addGroup(contatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typePhone2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneFormat2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FacebookText, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(facebookLabel))
                .addGap(18, 18, 18)
                .addGroup(contatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(typePhone3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(phoneFormat3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(twitterLabel)
                        .addComponent(twitterText, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        otherdatas.addTab("CONTATOS", contatos);

        questionarioSC.setViewportView(questionarioSCPanel);
        questionarioSC.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        questionarioSC.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jLabel15.setText("1 - Está disposto a se submeter e obedecer as exigêcias e normas estabelecidas pelos instrutores?");

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SIM", "NÃO" }));

        jLabel16.setText("2 - Promete respeitar os seus colegas e superiores?");

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SIM", "NÃO" }));

        jLabel17.setText("3 - Fará todo esforço possível para adquirir o fardamento?");

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SIM", "NÃO" }));

        jLabel18.setText("4 - Compromete-se a não faltar reuniões e atividades relacionadas ao Departamento?");

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SIM", "NÃO" }));

        jLabel19.setText("5 - Caso desista de continuarno Departamento doará seu fardamento a outro membro?");

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SIM", "NÃO" }));

        jLabel20.setText("6 - compromete-se a aprender os Juramentos, Hino Oficial e Divisa?");

        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SIM", "NÃO" }));

        jLabel21.setText("7 - Colaborará para o bom andamento do Soldado de Cristo?");

        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SIM", "NÃO" }));

        jLabel22.setText("8 - Compromete-se a convidar outros colegas e familiares?");

        jComboBox12.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SIM", "NÃO" }));

        javax.swing.GroupLayout questionarioSCPanelLayout = new javax.swing.GroupLayout(questionarioSCPanel);
        questionarioSCPanel.setLayout(questionarioSCPanelLayout);
        questionarioSCPanelLayout.setHorizontalGroup(
            questionarioSCPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionarioSCPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(questionarioSCPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(questionarioSCPanelLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(questionarioSCPanelLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(questionarioSCPanelLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(questionarioSCPanelLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(questionarioSCPanelLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(questionarioSCPanelLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(questionarioSCPanelLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(questionarioSCPanelLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(384, Short.MAX_VALUE))
        );
        questionarioSCPanelLayout.setVerticalGroup(
            questionarioSCPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionarioSCPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(questionarioSCPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(questionarioSCPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(questionarioSCPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(questionarioSCPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(questionarioSCPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(questionarioSCPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jComboBox10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(questionarioSCPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jComboBox11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(questionarioSCPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jComboBox12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        questionarioSC.setViewportView(questionarioSCPanel);

        otherdatas.addTab("QUESTIONÁRIO SC", questionarioSC);

        QSClabel1.setText("1 - Quantas pessoas compõem a sua família, incluindo você?");

        QSClabel2.setText("2 - Qual é o tipo de residência de sua família?");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Própria", "Alugada", "Emprestada" }));

        QSClabel3.setText("3 - Estado civil dos pais?");

        jComboBox13.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Casados", "Divorciados", "Vivem em casas separadas", "Outro" }));

        QSClabel4.setText("4 - Qual a renda mensal média de sua família hoje?");

        jComboBox14.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Até R$ 700,00", "De R$ 700,00 até R$ 1000,00", "De R$ 1000,00 até R$ 1500,00", "De R$ 1500,00 até R$ 2000,00", "Acima de R$ 2000,00", "Não possui nenhuma renda" }));

        QSClabel5.setText("5 - Qual tipo de trabalho é realizado?");

        fatherLabelSE.setText("PAI");

        jComboBox15.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Assalariado", "Aposentado", "Pensionista", "Dono de casa", "Outro" }));

        motherLabelSE.setText("MÃE");

        jComboBox16.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Assalariada", "Aposentada", "Pensionista", "Dona de casa", "Outro" }));

        QSClabel6.setText("6 - Como conheceu o Departamento Soldados de Cristo?");

        jComboBox17.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mídias digitais e propagandas (Sites, Redes Sociais, Rádio, Televisão)", "Através de desfiles e apresentações (7 de Setembro, Formaturas)", "Através do convite de amigos ou familiares", "Outro" }));

        QSClabel7.setText("7 - Recebe algum auxílio ou programa Social?");

        jComboBox18.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bolsa família", "Pensão ", "Auxílio doença", "Outro" }));

        QSClabel8.setText("8 - Alguém de sua família está doente?");

        jComboBox19.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SIM", "NÃO" }));

        QSClabel9.setText("9 - De qual enfermidade está acometido?");

        jComboBox20.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Diabetes", "Pressão Alta", "Doenças do Coração", "Reumatismo", "Câncer", "Depressão", "Outra" }));

        QSClabel10.setText("10 - Qual o nível de escolaridade?");

        jLabel27.setText("PAI");

        jLabel28.setText("MÃE");

        jComboBox21.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ensino Fundamental", "Ensino Médio", "Ensino Superior", "Mestre", "Doutor", "Outro" }));

        jComboBox23.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ensino Fundamental", "Ensino Médio", "Ensino Superior", "Mestre", "Doutor", "Outro" }));

        QSClabel11.setText("11 - Alguém fuma em sua família?");

        jComboBox24.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SIM", "NÃO" }));

        QSClabel12.setText("12 - Tem algum familiar envolvido com o Alcolismo?");

        jComboBox25.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SIM", "NÃO" }));

        QSClabel13.setText("13 - Professa alguma religião?");

        jComboBox26.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SIM", "NÃO" }));

        jLabel29.setText("Qual?");

        jTextField4.setText("Religião");

        javax.swing.GroupLayout questionarioSEPanelLayout = new javax.swing.GroupLayout(questionarioSEPanel);
        questionarioSEPanel.setLayout(questionarioSEPanelLayout);
        questionarioSEPanelLayout.setHorizontalGroup(
            questionarioSEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionarioSEPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(questionarioSEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(QSClabel1)
                    .addComponent(QSClabel2)
                    .addComponent(QSClabel3)
                    .addComponent(QSClabel4)
                    .addComponent(QSClabel5)
                    .addComponent(QSClabel6)
                    .addComponent(QSClabel7)
                    .addComponent(QSClabel8)
                    .addComponent(QSClabel9)
                    .addComponent(QSClabel10)
                    .addComponent(QSClabel11)
                    .addComponent(QSClabel12)
                    .addComponent(QSClabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(questionarioSEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(questionarioSEPanelLayout.createSequentialGroup()
                        .addComponent(jComboBox26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jComboBox25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(questionarioSEPanelLayout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jComboBox20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(questionarioSEPanelLayout.createSequentialGroup()
                        .addComponent(fatherLabelSE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(motherLabelSE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jComboBox14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        questionarioSEPanelLayout.setVerticalGroup(
            questionarioSEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionarioSEPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(questionarioSEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QSClabel1)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(questionarioSEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(QSClabel2)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(questionarioSEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(QSClabel3)
                    .addComponent(jComboBox13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(questionarioSEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(QSClabel4)
                    .addComponent(jComboBox14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(questionarioSEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(QSClabel5)
                    .addGroup(questionarioSEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fatherLabelSE)
                        .addComponent(jComboBox15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(motherLabelSE)
                        .addComponent(jComboBox16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(questionarioSEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QSClabel6)
                    .addComponent(jComboBox17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(questionarioSEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QSClabel7)
                    .addComponent(jComboBox18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(questionarioSEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QSClabel8)
                    .addComponent(jComboBox19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(questionarioSEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QSClabel9)
                    .addComponent(jComboBox20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(questionarioSEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QSClabel10)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28)
                    .addComponent(jComboBox21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(questionarioSEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QSClabel11)
                    .addComponent(jComboBox24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(questionarioSEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QSClabel12)
                    .addComponent(jComboBox25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(questionarioSEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QSClabel13)
                    .addComponent(jComboBox26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        questionarioSE.setViewportView(questionarioSEPanel);

        otherdatas.addTab("QUESTIONÁRIO SÓCIO-ECONÔMICO", questionarioSE);

        questionarioP.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        QPlabel1.setText("1 - Qual a sua cor?");

        jComboBox22.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Branco", "Negro", "Pardo", "Outro" }));

        QPlabel2.setText("2 - O membro possui algum tipo de enfermidade?");

        jComboBox27.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SIM", "NÃO" }));

        QPlabel3.setText("3 - Ele Possui algum tipo de alergia? ");

        jLabel30.setText("Qual?");

        jComboBox28.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Diabetes", "Pressão Alta", "Doenças do Coração", "Reumantismo", "Câncer", "Depressão", "Asma", "Outra" }));

        jComboBox29.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SIM", "NÃO" }));

        jLabel31.setText("Qual?");

        jComboBox30.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Respiratória", "Alimentar", "Insetos", "Medicamento", "Outro" }));

        QPlabel4.setText("4 - O membro toma algum medicamento?");

        jComboBox31.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SIM", "NÃO" }));

        jLabel32.setText("Qual?");

        QPlabel5.setText("5 - Professa alguma religião?");

        jComboBox32.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SIM", "NÃO" }));

        jLabel33.setText("Qual?");

        jLabel34.setText("6 - Por que deseja ser um soldado de Cristo?");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(jTextArea1);

        javax.swing.GroupLayout quetionarioPpanelLayout = new javax.swing.GroupLayout(quetionarioPpanel);
        quetionarioPpanel.setLayout(quetionarioPpanelLayout);
        quetionarioPpanelLayout.setHorizontalGroup(
            quetionarioPpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quetionarioPpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(quetionarioPpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(quetionarioPpanelLayout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4))
                    .addGroup(quetionarioPpanelLayout.createSequentialGroup()
                        .addGroup(quetionarioPpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(QPlabel5)
                            .addComponent(QPlabel2)
                            .addComponent(QPlabel4)
                            .addComponent(QPlabel1)
                            .addComponent(QPlabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(quetionarioPpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(quetionarioPpanelLayout.createSequentialGroup()
                                .addComponent(jComboBox29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel31)
                                .addGap(25, 25, 25)
                                .addComponent(jComboBox30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComboBox22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(quetionarioPpanelLayout.createSequentialGroup()
                                .addComponent(jComboBox27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel30)
                                .addGap(25, 25, 25)
                                .addComponent(jComboBox28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(quetionarioPpanelLayout.createSequentialGroup()
                                .addGroup(quetionarioPpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(quetionarioPpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(quetionarioPpanelLayout.createSequentialGroup()
                                        .addComponent(jLabel32)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(quetionarioPpanelLayout.createSequentialGroup()
                                        .addComponent(jLabel33)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(413, Short.MAX_VALUE))
        );
        quetionarioPpanelLayout.setVerticalGroup(
            quetionarioPpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quetionarioPpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(quetionarioPpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QPlabel1)
                    .addComponent(jComboBox22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(quetionarioPpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(quetionarioPpanelLayout.createSequentialGroup()
                        .addGroup(quetionarioPpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(QPlabel2)
                            .addComponent(jComboBox27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30)
                            .addComponent(jComboBox28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(quetionarioPpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31)
                            .addComponent(jComboBox30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(QPlabel3))
                        .addGap(18, 18, 18)
                        .addGroup(quetionarioPpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(quetionarioPpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jComboBox31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel32)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(QPlabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(quetionarioPpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(QPlabel5)))
                    .addGroup(quetionarioPpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel33)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(quetionarioPpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        questionarioP.setViewportView(quetionarioPpanel);

        otherdatas.addTab("QUESTIONÁRIO PESSOAL", questionarioP);

        saveButton.setText("Cadastrar");
        saveButton.setPreferredSize(new java.awt.Dimension(81, 25));
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        titleLabel.setText("CADASTRO DE MEMBROS - N BATALHÃO");

        clearButton.setText("Limpar");
        clearButton.setPreferredSize(new java.awt.Dimension(81, 25));
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        helpLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/sc/SystemImages/iconeDuvida.png"))); // NOI18N
        helpLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                helpLabelMouseClicked(evt);
            }
        });

        statusProgress.setOpaque(true);
        statusProgress.setPreferredSize(new java.awt.Dimension(145, 25));
        statusProgress.setStringPainted(true);

        uploadPhotoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/sc/SystemImages/upPhoto.png"))); // NOI18N
        uploadPhotoLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                uploadPhotoLabelMouseClicked(evt);
            }
        });

        infoPhoto.setText("Carregar Foto 3 X 4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(titleLabel)
                .addContainerGap(241, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(otherdatas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(statusProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(helpLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(photoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(infoPhoto)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(uploadPhotoLabel)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(personaldata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(personaldata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(photoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(uploadPhotoLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(infoPhoto)))))
                .addGap(18, 18, 18)
                .addComponent(otherdatas, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(helpLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(statusProgress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void uploadPhotoLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uploadPhotoLabelMouseClicked
        // TODO add your handling code here:
        List<FileFilter> filters = new ArrayList<FileFilter>();
        filters.add(new FileNameExtensionFilter("jpg files", "jpg"));
        filters.add(new FileNameExtensionFilter("png files", "png"));
        try {      
            photoPath = getArchiveDialog("Selecione a Foto desejada", filters, FOTO);
        } catch (Exception ex) {
            showDialogInfo(ex.getMessage());
        }
    }//GEN-LAST:event_uploadPhotoLabelMouseClicked

    
    //Método para mostrar uma messagem com JOptionPane
    private void showDialogInfo(String message){
                JOptionPane.showMessageDialog(this, message);
    }
    
    /**
     * Método para inserir na label da foto 3x4 o arquivo pego na dialogInput
     * @param pathFoto 
     */
    private void setImageFromDialog(String pathFoto) {
        ImageIcon image = new ImageIcon(pathFoto);
        image.setImage(image.getImage().getScaledInstance(150, 164, 0));
        photoLabel.setIcon(image);
    }

    /**
     * Esse método abre uma caixa de Diálogo para pegar um arquivo
     * @param title Título que irá aparecer na caixa de diálogo
     * @param filt É um array com N filtros utilizados na caixa de diálogo
     * @param tp É o tipo do arquivo requerido
     * @return a String com o PATH do arquivo
     */
    private String getArchiveDialog(String title, List<FileFilter> filt, int tp) throws Exception{
        int retorno;
        String pathReturn = "";
        openFile = new JFileChooser();
        openFile.setDialogTitle(title);
        int i = 0;
        int tamFile = getTamanho(tp);
        while(i < filt.size()){
            openFile.addChoosableFileFilter(filt.get(i));
            i++;
        }
        retorno = openFile.showOpenDialog(null);
        if (retorno == JFileChooser.APPROVE_OPTION) {
            pathReturn = openFile.getSelectedFile().getAbsolutePath();
            if (!validarArchiveByDialog(pathReturn, tp)) {
                throw new Exception("Tamanho limite excedido!\nO tamanho máximo do arquivo é de: "+tamFile+"Kb");
            }
           
        }   
        return pathReturn;
    }
    
    /**
     * Esse método valida o tamanho do arquivo, de acordo com os tamanhos pré-definidos
     * @param path é o caminho do arquivo
     * @param type É o tipo do arquivo(FOTO - 0; DOCUMENTO - 1)
     * @return true, caso seja possível e false c.c.
     */
    private boolean validarArchiveByDialog(String path, int tam){
        File file = new File(path);
        if (file.getUsableSpace() > tam) {//Verificar aqui, pois o resultado desse método não retorna em KB
            System.err.println(file.getUsableSpace());
            return false;
        }        
        return true;           
    }
    
    private int getTamanho(int type){
        return type==FOTO?MAX_TAM_FOTO:MAX_TAM_DOCUMENTO;
    }
    
    
    private void emailTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTextFocusLost
        // TODO add your handling code here:
        if (verifyEmailAddress(emailText.getText())) {
            validEmail.setForeground(Color.GREEN);
            validEmail.setText("OK");
        } else {
            validEmail.setForeground(Color.RED);
            validEmail.setText("INVÁLIDO");
        }

    }//GEN-LAST:event_emailTextFocusLost

    private void cepTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cepTextFocusLost
        // TODO add your handling code here:
        WebServiceCep webServiceCep = WebServiceCep.searchCep(cepText.getText().toString());
        //caso a busca ocorra bem, imprime os resultados.
        if (!DataBaseConnect.getTypeConn()) {
            validarCEP.setText("Sem conexão!");
        }else if (webServiceCep.wasSuccessful()) {
            validarCEP.setText("");
            streetText.setText(webServiceCep.getLogradouroFull());
            districtText.setText(webServiceCep.getBairro());
            cityText.setText(webServiceCep.getCidade());
            stateText.setText(webServiceCep.getUf());
            countryText.setText("Brasil");

            //caso haja problemas imprime as exceções.
        } else {
            validarCEP.setText("CEP inválido, tente novamente!");
            //System.out.println("Erro número: " + webServiceCep.getResulCode());
            //System.out.println("Descrição do erro: " + webServiceCep.getResultText());
        }
    }//GEN-LAST:event_cepTextFocusLost

    private void helpLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpLabelMouseClicked
        // TODO add your handling code here:
        dialogInfo.setVisible(true);
    }//GEN-LAST:event_helpLabelMouseClicked

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed

        int registryAux = 0;
        try {
            userRegistry = new UserRegistry(registryAux, nomeText.getText(), warNameText.getText(), Integer.parseInt(rgText.getText()), 
                    Integer.parseInt(batOption.getName()), batOption.getSelectedIndex(), photoPath, photoPath, 
                photoPath, WIDTH, photoPath, WIDTH, WIDTH, photoPath, photoPath, photoPath, photoPath, photoPath, photoPath, 
                photoPath, photoPath, photoPath, photoPath, WIDTH, photoPath, photoPath, photoPath, photoPath, null, photoPath, 
                null);            
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_saveButtonActionPerformed

    private boolean verifyEmailAddress(String emailAddress) {
        return emailAddress.matches("\\w+@[a-zA-Z_]+?\\.[a-zA-Z]{2,3}") && !emailAddress.equals("");

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FacebookText;
    private javax.swing.JLabel Nacionalidade;
    private javax.swing.JLabel QPlabel1;
    private javax.swing.JLabel QPlabel2;
    private javax.swing.JLabel QPlabel3;
    private javax.swing.JLabel QPlabel4;
    private javax.swing.JLabel QPlabel5;
    private javax.swing.JLabel QSClabel1;
    private javax.swing.JLabel QSClabel10;
    private javax.swing.JLabel QSClabel11;
    private javax.swing.JLabel QSClabel12;
    private javax.swing.JLabel QSClabel13;
    private javax.swing.JLabel QSClabel2;
    private javax.swing.JLabel QSClabel3;
    private javax.swing.JLabel QSClabel4;
    private javax.swing.JLabel QSClabel5;
    private javax.swing.JLabel QSClabel6;
    private javax.swing.JLabel QSClabel7;
    private javax.swing.JLabel QSClabel8;
    private javax.swing.JLabel QSClabel9;
    private javax.swing.JLabel RG;
    private javax.swing.JTextField UF;
    private javax.swing.JFormattedTextField bDayText;
    private javax.swing.JLabel bat;
    private javax.swing.JComboBox batOption;
    private javax.swing.JLabel birthDate;
    private javax.swing.JComboBox bloddTypeOption;
    private javax.swing.JLabel bloodType;
    private javax.swing.JLabel cepLabel;
    private javax.swing.JTextField cepText;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JTextField cityText;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel complementLabel;
    private javax.swing.JTextField complementText;
    private javax.swing.JPanel contatos;
    private javax.swing.JLabel countryLabel;
    private javax.swing.JTextField countryText;
    private javax.swing.JLabel cpf;
    private javax.swing.JFormattedTextField cpfText;
    private javax.swing.JDialog dialogInfo;
    private javax.swing.JLabel districtLabel;
    private javax.swing.JTextField districtText;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailText;
    private javax.swing.JPanel endereco;
    private javax.swing.JCheckBox fBox;
    private javax.swing.JLabel facebookLabel;
    private javax.swing.JLabel fatherLabelSE;
    private javax.swing.JLabel helpLabel;
    private javax.swing.JLabel infoPhoto;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox10;
    private javax.swing.JComboBox jComboBox11;
    private javax.swing.JComboBox jComboBox12;
    private javax.swing.JComboBox jComboBox13;
    private javax.swing.JComboBox jComboBox14;
    private javax.swing.JComboBox jComboBox15;
    private javax.swing.JComboBox jComboBox16;
    private javax.swing.JComboBox jComboBox17;
    private javax.swing.JComboBox jComboBox18;
    private javax.swing.JComboBox jComboBox19;
    private javax.swing.JComboBox jComboBox20;
    private javax.swing.JComboBox jComboBox21;
    private javax.swing.JComboBox jComboBox22;
    private javax.swing.JComboBox jComboBox23;
    private javax.swing.JComboBox jComboBox24;
    private javax.swing.JComboBox jComboBox25;
    private javax.swing.JComboBox jComboBox26;
    private javax.swing.JComboBox jComboBox27;
    private javax.swing.JComboBox jComboBox28;
    private javax.swing.JComboBox jComboBox29;
    private javax.swing.JComboBox jComboBox30;
    private javax.swing.JComboBox jComboBox31;
    private javax.swing.JComboBox jComboBox32;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JComboBox jComboBox7;
    private javax.swing.JComboBox jComboBox8;
    private javax.swing.JComboBox jComboBox9;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JCheckBox mBox;
    private javax.swing.JLabel motherLabelSE;
    private javax.swing.JTextField nacText;
    private javax.swing.JTextField natText;
    private javax.swing.JLabel naturalidade;
    private javax.swing.JLabel nome;
    private javax.swing.JTextField nomeText;
    private javax.swing.JLabel numberLabel;
    private javax.swing.JTextField numberText;
    private javax.swing.JTabbedPane otherdatas;
    private javax.swing.JComboBox patOption;
    private javax.swing.JLabel patente;
    private javax.swing.JPanel personaldata;
    private javax.swing.JFormattedTextField phoneFormat1;
    private javax.swing.JFormattedTextField phoneFormat2;
    private javax.swing.JFormattedTextField phoneFormat3;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JLabel photoLabel;
    private javax.swing.JPanel photoPanel;
    private javax.swing.JScrollPane questionarioP;
    private javax.swing.JScrollPane questionarioSC;
    private javax.swing.JPanel questionarioSCPanel;
    private javax.swing.JScrollPane questionarioSE;
    private javax.swing.JPanel questionarioSEPanel;
    private javax.swing.JPanel quetionarioPpanel;
    private javax.swing.JLabel redeSocialLabel;
    private javax.swing.JTextField rgText;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel sexo;
    private javax.swing.JLabel stateLabel;
    private javax.swing.JTextField stateText;
    private javax.swing.JLabel status;
    private javax.swing.JComboBox statusOption;
    private javax.swing.JProgressBar statusProgress;
    private javax.swing.JLabel streetLabel;
    private javax.swing.JTextField streetText;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel twitterLabel;
    private javax.swing.JTextField twitterText;
    private javax.swing.JComboBox typePhone1;
    private javax.swing.JComboBox typePhone2;
    private javax.swing.JComboBox typePhone3;
    private javax.swing.JLabel ufNat;
    private javax.swing.JLabel uploadPhotoLabel;
    private javax.swing.JLabel validEmail;
    private javax.swing.JLabel validarCEP;
    private javax.swing.JLabel warName;
    private javax.swing.JTextField warNameText;
    // End of variables declaration//GEN-END:variables
    private String photoPath;
    private JFileChooser openFile;
    
}
